- twitterName: joshwcomeau
  fullName: Josh W. Comeau
  url: https://a11y.coffee/
  pickName: A11y Coffee

- twitterName: swyx
  fullName: Shawn Wang
  url: https://svelte.dev/
  pickName: Svelte

- twitterName: kentcdodds
  fullName: Kent C. Dodds
  url: https://remix.run/
  pickName: Remix